spring.application.name=demo


# Oracle database connection
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=bank
spring.datasource.password=root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


#Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true